
/**
 * @fileOverview Trip schemas for Zod validation and TypeScript types.
 *
 * This file defines the structure of trip-related data, including individual legs,
 * the main trip object, and the inputs for saving and fetching trips.
 * It uses Zod for schema validation, ensuring data integrity across the application.
 */

import { z } from 'zod';

export const tripStatuses = ["Scheduled", "Confirmed", "En Route", "Completed", "Cancelled", "Diverted", "Delayed", "Awaiting Closeout", "Released", "Booked"] as const;
export const tripTypes = ["Part 135", "Part 91", "Part 121", "Medical", "Cargo", "Ferry"] as const;
export const legStatuses = ["Scheduled", "En Route", "Completed", "Cancelled", "Diverted"] as const;

/**
 * @typedef TripLeg
 * @property {string} id - Unique identifier for the leg.
 * @property {string} origin - ICAO code of the origin airport.
 * @property {string} destination - ICAO code of the destination airport.
 * @property {string} departureDateTime - ISO string of the departure time.
 * @property {string} arrivalDateTime - ISO string of the arrival time.
 * @property {number} paxCount - Number of passengers on this leg.
 * @property {string} status - Status of the individual leg.
 * @property {number} [blockTimeHours] - Estimated or actual block time in hours.
 * @property {number} [flightTimeHours] - Estimated or actual flight time in hours.
 */
export const TripLegSchema = z.object({
  id: z.string().optional().describe("Unique identifier for the trip leg, typically a UUID."),
  origin: z.string().min(3, "Origin airport code is required.").max(4, "Origin airport code is too long.").describe("ICAO code for the origin airport (e.g., KLAX)."),
  destination: z.string().min(3, "Destination airport code is required.").max(4, "Destination airport code is too long.").describe("ICAO code for the destination airport (e.g., KJFK)."),
  departureDateTime: z.string().datetime({ message: "Invalid departure datetime format." }).describe("ISO 8601 string for the planned departure time."),
  arrivalDateTime: z.string().datetime({ message: "Invalid arrival datetime format." }).optional().describe("ISO 8601 string for the planned arrival time."),
  paxCount: z.number().int().min(0, "Passenger count cannot be negative.").default(0).describe("Number of passengers for this leg."),
  status: z.enum(legStatuses).default("Scheduled").describe("Current status of this specific leg."),
  blockTimeHours: z.number().optional().describe("Block time in hours for this leg."),
  flightTimeHours: z.number().optional().describe("Flight time in hours for this leg."),
});
export type TripLeg = z.infer<typeof TripLegSchema>;


export const TripSchema = z.object({
    id: z.string().describe("Unique identifier for the trip document, auto-generated by Firestore."),
    tripId: z.string().describe("User-facing unique identifier for the trip."),
    
    // Core Trip Details
    clientId: z.string().optional().describe("ID of the associated client/customer."),
    clientName: z.string().optional().describe("Name of the client, stored for display convenience."),
    aircraftId: z.string().min(1, "Aircraft is required.").describe("ID of the assigned aircraft."),
    aircraftLabel: z.string().optional().describe("Label of the aircraft (e.g., N123AB - Cessna CJ3), stored for display convenience."),
    tripType: z.enum(tripTypes).default("Part 135"),
    legs: z.array(TripLegSchema).min(1, "A trip must have at least one leg."),
    
    status: z.enum(tripStatuses).default("Scheduled"),
    
    // Crew assignments for the overall trip
    assignedPilotId: z.string().optional().describe("ID of the assigned Pilot in Command (PIC)."),
    assignedCoPilotId: z.string().optional().describe("ID of the assigned Second in Command (SIC) / Co-Pilot."),
    assignedFlightAttendantIds: z.array(z.string()).optional().default([]).describe("IDs of assigned Flight Attendants."),
    assignedMedicalCrewIds: z.array(z.string()).optional().default([]).describe("IDs of assigned medical crew (e.g., Paramedics, Nurses)."),
  
    notes: z.string().optional().describe("Internal notes about the trip."),
    
    createdAt: z.string().describe("ISO string format, server-generated timestamp."),
    updatedAt: z.string().describe("ISO string format, server-generated timestamp."),
  });
  export type Trip = z.infer<typeof TripSchema>;

/**
 * @typedef SaveTripInput
 * @description Excludes server-generated fields like `id`, `createdAt`, `updatedAt`.
 */
export const SaveTripInputSchema = TripSchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type SaveTripInput = z.infer<typeof SaveTripInputSchema>;
export const SaveTripOutputSchema = TripSchema;
export type SaveTripOutput = z.infer<typeof SaveTripOutputSchema>;


/**
 * @typedef FetchTripsOutput
 * @description Output schema for fetching multiple trips.
 */
export const FetchTripsOutputSchema = z.array(TripSchema);
export type FetchTripsOutput = z.infer<typeof FetchTripsOutputSchema>;

/**
 * @typedef FetchTripByIdInput
 * @description Input schema for fetching a single trip by its document ID.
 */
export const FetchTripByIdInputSchema = z.object({
  id: z.string(),
});
export type FetchTripByIdInput = z.infer<typeof FetchTripByIdInputSchema>;

/**
 * @typedef DeleteTripInput
 * @description Input schema for deleting a trip.
 */
export const DeleteTripInputSchema = z.object({
    id: z.string(),
});
export type DeleteTripInput = z.infer<typeof DeleteTripInputSchema>;
  
export const DeleteTripOutputSchema = z.object({
    success: z.boolean(),
    tripId: z.string(),
});
export type DeleteTripOutput = z.infer<typeof DeleteTripOutputSchema>;
